### ISSUE TITLE
ttfGetExtents off-by-1 bug

### ISSUE THREAD

**Issue by zacii7** [michaelrsweet/ttf#1]
the provided helper function `ttfGetExtents` gives the incorrect width. it is calculating based on the width of the alphabetically preceding character.

as can be clearly seen in the following sample

[p.pdf](https://github.com/michaelrsweet/pdfio/files/12791574/p.pdf)

**Comment by michaelrsweet** [comment]
[master 8acbdee] Fix off-by-one error (Issue #1)

[master 88fbf78] Merge changes from PDFio.

**Comment by zacii7** [comment]
I'm still not getting correct numbers. it is now working for regular alpha-numerics, but space, euro, and other accented characters are still off. (i just checked now and i see the original version was getting it correct for euro)

**Comment by michaelrsweet** [comment]
Hmm, might be an issue with the cmap table support... Reopening to investigate further...

**Comment by michaelrsweet** [comment]
[master 042a288] Fix font widths (Issue #1)

**Comment by zacii7** [comment]
thank you for looking into this. maybe there is something strange going on with the fonts I was given to work with. everything is ok except the space character, which reports its width as 0, and doesnt seem to be present in `font->widths`

[fonts.zip](https://github.com/michaelrsweet/ttf/files/13375621/fonts.zip)

**Comment by zacii7** [comment]
I also notice in your OpenSans test file, '€' gives width 0, and in NotoSansJP it gives an incorrect number. the neo_sans font I have does get euro correct.

**Comment by michaelrsweet** [comment]
I'm

**Comment by michaelrsweet** [comment]
[master bb3027d] Fix the CMAP format 4 decoder for idRangeOffset (Issue #1)

OK, I think I have this fixed (at least for the fonts you attached) - the cmap decoder wasn't handling the idRangeOffset stuff properly (documentation on this sucks, and the offset stuff is such a hack...) Let me know if you see any other issues.

**Comment by zacii7** [comment]
yes, this is looking much better now. the alignments and paragraphing are as they should be.
Thanks a lot for your time and efforts in fixing this and for making the library available.
